### ISSUE TITLE
What still works?

### ISSUE THREAD

**Issue by camerafun** [GoogleChromeLabs/web-gphoto2#5] opened 2023-06-19 00:37 UTC
Hey, thanks for putting this project together. It seems like a lot of stuff may have bitrotted and no longer works. Can you please help point me in the right direction to begin fixing any portion of this project?

1. Your website demo displays the following error in Chrome Developer tools: "Error with Permissions-Policy header"

2. Building this project by running ./build.sh leads to autoconf errors
<pre>
./configure: line 4408: LT_INIT: command not found
./configure: line 4409: syntax error near unexpected token `Windows'
./configure: line 4409: `LT_LANG(Windows Resource)'
make: *** [Makefile:40: deps/libusb/Makefile] Error 2
make: *** Waiting for unfinished jobs....
autoreconf: running: aclocal --force -I auto-m4 -I gphoto-m4
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'auto-aux'.
libtoolize: copying file 'auto-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'auto-m4'.
libtoolize: copying file 'auto-m4/libtool.m4'
libtoolize: copying file 'auto-m4/ltoptions.m4'
libtoolize: copying file 'auto-m4/ltsugar.m4'
libtoolize: copying file 'auto-m4/ltversion.m4'
libtoolize: copying file 'auto-m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:73: installing 'auto-aux/compile'
configure.ac:13: installing 'auto-aux/missing'
Makefile.am: installing 'auto-aux/depcomp'
autoreconf: Leaving directory `libgphoto2_port'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'auto-aux'.
libtoolize: copying file 'auto-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'auto-m4'.
libtoolize: copying file 'auto-m4/libtool.m4'
libtoolize: copying file 'auto-m4/ltoptions.m4'
libtoolize: copying file 'auto-m4/ltsugar.m4'
libtoolize: copying file 'auto-m4/ltversion.m4'
libtoolize: copying file 'auto-m4/lt~obsolete.m4'
configure.ac:110: installing 'auto-aux/compile'
configure.ac:17: installing 'auto-aux/missing'
camlibs/Makefile.am: installing 'auto-aux/depcomp'
autoreconf: Leaving directory `.'
rm deps/libgphoto2/configure
emmake: error: 'make -j8' failed (returned 2)
</pre>

4. Libusb fails to run in Chrome. Many functions and vals don't resolve or throw exceptions like "caller is not a function"

Is there any way to get any of these libraries or demos to work again?

**Comment by RReverser** [comment] 2023-06-19 11:58
Hi, this was an interesting project indeed but I no longer work at Google and in terms of side-projects I'm full at the moment and probably won't look at this in the nearest time.

If there's commercial interest, I'm happy to help out as I'm working as a contractor these days, otherwise your best bet is to try and fix those in a PR and I should be able to merge.

**Comment by RReverser** [comment] 2023-08-05 17:51
> * Your website demo displays the following error in Chrome Developer tools: "Error with Permissions-Policy header"
> *

FWIW I just tried with latest stable Chrome and I don't see any errors - the website is still working as intended and I could connect to my Canon camera.

`./build.sh` also works as intended - from your messages like "./configure: line 4409: syntax error near unexpected token `Windows`
 it seems you were trying to build it on Windows, but I'm pretty sure it won't work / it's not supported as Windows doesn't have all the necessary ports. On Linux the project still seems to build (UPD actually seeing one issue, but maybe that's just local tooling).

Given that I can't repro either of the issues, I'm going to close this.

**Closed as completed by RReverser** 2023-08-05 17:51 UTC
